repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
  - repo: local
    hooks:
      - id: sort-json-files
        name: sort JSON files
        entry: scripts/sort-json-file.sh
        language: system
        files: \.json$
